#!/usr/bin/env python

Import("env")
Import("env_modules")

ecs = env_modules.Clone()


# Module source files
ecs.add_source_files(env.modules_sources, "components/*.cpp")
ecs.add_source_files(env.modules_sources, "component_storages/*.cpp")
ecs.add_source_files(env.modules_sources, "*.cpp")

ecs.add_source_files(env.modules_sources, "editor_plugins/*.cpp")
